version: '3.8'

services:

  db:
    image: mysql
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_USER: giang
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: post_service