version: '3.8'

services:

  db:
    image: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: giang
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user-service
  app:
    image: 'user-service:lastest'
    build:
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    container_name: user-service
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3307/user-service
      - SPRING_DATASOURCE_USERNAME = giang
      - SPRING_DATASOURCE_PASSWORD = password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    network_mode: bridge
networks:
  default:
    driver: bridge